/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-18 08:47:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.BoardDAO;
import dao.BoardObj;
import java.util.*;
import dao.*;

public final class detailBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1637166678000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1637225258000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.BoardObj");
    _jspx_imports_classes.add("dao.BoardDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/font.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("   font-family: 'Jeju Myeongjo', serif;\r\n");
      out.write("   font-size: 35px;\r\n");
      out.write("    margin-left: 40px;\r\n");
      out.write("    margin-right: 40px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    margin: 0px 15px;\r\n");
      out.write("    padding: 28px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("  font-size: 1.125rem;\r\n");
      out.write("  text-anchor: middle;\r\n");
      out.write("  -webkit-user-select: none;\r\n");
      out.write("  -moz-user-select: none;\r\n");
      out.write("  -ms-user-select: none;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a , a:hover {\r\n");
      out.write("	color: #000000;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"/main.jsp\">AWESOME PLACE</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarScroll\" aria-controls=\"navbarScroll\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarScroll\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll\" style=\"--bs-scroll-height: 100px;\">\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown\" href=\"#\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            	어썸플레이스 소개\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/intro/intro.jsp\">카페연혁</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/intro/branch.jsp\">매장찾기</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown\" href=\"#\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            	메뉴이야기\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/menu/mCoffee.jsp\">COFFEE</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/menu/mTea.jsp\">TEA</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/menu/mDessert.jsp\">DESSERT</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown\" href=\"#\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            	게시판\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/event/eventList.jsp\">공지사항 및 이벤트</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/board/listBoard.jsp\">게시판</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("		 </ul>\r\n");
      out.write("<!-- 		 로그인 버튼 맨 우측으로 보내기 -->\r\n");
      out.write("			<ul class=\"nav justify-content-end\"> \r\n");
      out.write("			  <li class=\"nav-item dropdown\">\r\n");
      out.write("		");

		// 현재 로그인 된 아이디 세션
			String userID = null;
			if (session.getAttribute("id") != null) {
				userID = (String) session.getAttribute("id");
			}
			
			if (userID == null) {
		
      out.write("\r\n");
      out.write("		          <a class=\"nav-link dropdown\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		            	회원관리\r\n");
      out.write("		          </a>\r\n");
      out.write("		          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/Login.jsp\">로그인</a></li>\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/Join.jsp\">회원가입</a></li>\r\n");
      out.write("		          </ul>\r\n");
      out.write("		");

			// 관리자 아이디일 때
			} else if (userID != null && userID.equals("admin")) {
		
      out.write("\r\n");
      out.write("				  <a class=\"nav-link dropdown\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		            	");
      out.print(userID );
      out.write("님, 환영합니다!\r\n");
      out.write("		          </a>\r\n");
      out.write("		          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/Logout.jsp\">로그아웃</a></li>\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/ListMember.jsp\">회원관리</a></li>\r\n");
      out.write("		          </ul>\r\n");
      out.write("		");

			// 일반 아이디
			} else {
		
      out.write("\r\n");
      out.write("		          <a class=\"nav-link dropdown\" id=\"navbarScrollingDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("		            	");
      out.print(userID );
      out.write("님, 환영합니다!\r\n");
      out.write("		          </a>\r\n");
      out.write("		          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarScrollingDropdown\">\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/Logout.jsp\">로그아웃</a></li>\r\n");
      out.write("		            <li><a class=\"dropdown-item\" href=\"/member/myListMember.jsp\">회원탈퇴</a></li>\r\n");
      out.write("		          </ul>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		        </li>\r\n");
      out.write("	        </ul>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("<div class=\"alert alert-secondary\" role=\"alert\">\r\n");
      out.write("			<h1>게시판</h1>\r\n");
      out.write("</div>\r\n");

	request.setCharacterEncoding("utf-8");

	String a = request.getParameter("id");

	BoardObj board = (new BoardDAO()).getDetail(a);


      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<table class=\"table table-striped\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th colspan=\"2\" style=\"background-color: #eeeeee; text-align: center;\">게시판 글 보기</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 20%;\">글 제목</td>\r\n");
      out.write("					<td colspan=\"2\">");
      out.print( board.getTitle());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>작성자</td>\r\n");
      out.write("					<td colspan=\"2\">");
      out.print( board.getMember() );
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>작성일자</td>\r\n");
      out.write("					<td colspan=\"2\">");
      out.print( board.getDate());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					if (board.getFilename() != null) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" style=\"height: 200px; text-align: center;\">\r\n");
      out.write("						<img src=\"/images/");
      out.print(board.getFilename());
      out.write("\" style=\"width: 65%\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					} else {
				
      out.write("\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>내용</td>\r\n");
      out.write("					<td colspan=\"2\" style=\"height: 200px; text-align: left;\">");
      out.print( board.getDescription());
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class=\"d-grid gap-2 d-md-flex justify-content-md-end\">\r\n");
      out.write("			  <a href=\"/board/listBoard.jsp\" class=\"btn btn-secondary\">목록</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".insta-text{\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write(".insta-img{\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("	<p class=\"text insta-text\" align=\"right\">\r\n");
      out.write("		instagram<br>\r\n");
      out.write("		awesome_c_place\r\n");
      out.write("	<div class=\"insta-img\" align=\"right\">\r\n");
      out.write("		<a href=\"https://www.instagram.com/awesome_c_place/\" target=\"blank\">\r\n");
      out.write("		<img src=\"/resource/images/bg/insta.png\">\r\n");
      out.write("		</a>\r\n");
      out.write("   	</div>\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
